### ISSUE TITLE
The equation defining the BetaFactory estimator is wrong in the doc

### ISSUE THREAD

**Issue by mbaudin47** [openturns/openturns#1389]
The equation in:

http://openturns.github.io/openturns/latest/user_manual/_generated/openturns.BetaFactory.html

![Screenshot from 2020-02-28 23-10-07](https://user-images.githubusercontent.com/31351465/75591247-86f87e00-5a7f-11ea-9ed0-0e32c051f2e5.png)

* The expression $x_{1,n}$ is undefined in the equation for $\hat{a}_n$ (the minimum ?).
* The expression $x_{n,n}$ is undefined in the equation for $\hat{b}_n$ (the maximum ?).
* The expression $\sigma^X_n$ is undefined (the standard deviation ?).
* The equation for $\hat{r}_n$ uses $t$, but we may guess that $\hat{t}_n$ was meant. 
* The expression $\bar{x}_n$ is undefined (the empirical mean ?).

**Comment by jschueller** [comment]
Yes, this is a convention

**Comment by josephmure** [comment]
I think this issue is now resolved, isn't it? What do you think @mbaudin47 ?

**Comment by sofianehaddad** [comment]
Absolutely! We changed both implementation and notations.
I close the issue. Feel free to reopen it if required...

**Comment by mbaudin47** [comment]
You are right. I fixed it at 4b5a516c1fb57c4d943dcc9d6fdfbe769f4e2d22 and forgot to mention this issue in the PR #1428 and the commit message. My fault: sorry.

**Comment by mbaudin47** [comment]
Damned, the issue is not fixed. I open a specific issue to make it clearer: #1725.
