### ISSUE TITLE
The `StandardEvent` class deserves a full-length example

### ISSUE THREAD

**Issue by mbaudin47** [openturns/openturns#1722]
The FORM/SORM recipe has several ingredients, but certainly one of the most fundamental is the transformation from physical space to U-space. This is performed by the `StandardEvent` class. The API doc has an example, and some examples are presented using this class, but no full-length example shows how the function performs and how it affects the distributions. 
At least two examples should be presented:
* a simple example with a Gaussian distribution and a non diagonal covariance,
* a more complex example with non-gaussian marginals and a non-Gaussian copula.
The text should emphasize the main property of the transformation, that is, the rotational invariance.

**Comment by mbaudin47** [comment]
The following is a complete example.
```
import openturns as ot
import openturns.viewer as otv

def view_graph(graph):
    view = otv.View(graph)
    figure = view.getFigure()
    ax = figure.get_axes()[0]
    ax.axis("equal")
    return figure

# Set the X distribution
mu = [10.0] * 2
sigma = [3.0] * 2
R = ot.CorrelationMatrix([[1.0, 0.5], [0.5, 1.0]])
c = ot.NormalCopula(R)
X1 = ot.Normal(mu[0], sigma[0])
X1.setDescription([r"$x_1$"])
X2 = ot.Normal(mu[1], sigma[1])
X2.setDescription([r"$x_2$"])
distribution_X = ot.ComposedDistribution([X1, X2], c)

# Get the distribution of X
distribution_U = distribution_X.getStandardDistribution()
distribution_U.setDescription([r"$u_1$", r"$u_2$"])

# Draw PDF in X-space
graph = distribution_X.drawPDF()
view_graph(graph)

# Draw PDF in U-space
graph = distribution_U.drawPDF()
view_graph(graph)

# Maps a sample from X into U
sample_X = distribution_X.getSample(100)
transformation = distribution_X.getIsoProbabilisticTransformation()
sample_U = transformation(sample_X)

# Plot sample X
graph = ot.Graph("Sample in physical space.", r"$x_1$", r"$x_2$", True)
cloud = ot.Cloud(sample_X)
graph.add(cloud)
view_graph(graph)

# Plot sample U
graph = ot.Graph("Sample in standard space.", r"$u_1$", r"$u_2$", True)
cloud = ot.Cloud(sample_U)
graph.add(cloud)
view_graph(graph)

# Set the function
formula = "2.5 - (x1 - x2) + (x1 + x2)^2"
limitStateFunction = ot.SymbolicFunction(["x1", "x2"], [formula])

# Set event
threshold = 0.0
random_vector = ot.RandomVector(distribution_X)
lsf_random_vector = ot.CompositeRandomVector(limitStateFunction, random_vector)
event = ot.ThresholdEvent(lsf_random_vector, ot.LessOrEqual(), threshold)

# Compute event in U-space
myStandardEvent = ot.StandardEvent(event)
```
It produces the following figures.
![image](https://user-images.githubusercontent.com/31351465/104963818-9b1cd500-59db-11eb-8672-ce92ed32a4d1.png)

![image](https://user-images.githubusercontent.com/31351465/104963825-9d7f2f00-59db-11eb-8636-c24cd51a81f6.png)

![image](https://user-images.githubusercontent.com/31351465/104964345-88ef6680-59dc-11eb-9f17-5f240fb1c39b.png)

![image](https://user-images.githubusercontent.com/31351465/104964361-8c82ed80-59dc-11eb-83c0-cb42befcbd33.png)

**Comment by regislebrun** [comment]
Nice example. You mean "get the distribution of U" in the comment just before to ask X for its standard distribution? Note also that the view_graph function is useless: you can ask for square axes when creating a View object. You just have to pass square_axes=True to the constructor:
```
otv.View(graph, square_axes=True)
```
The effect on the sample would be more visible using a larger sample but with a smaller symbol. Try a sample size of 1000 with the dot point style:
```
cloud = ot.Cloud(sample_X)
cloud.setPointStyle("dot")
```
For non-Gaussian elliptical distributions such as:
```
mu = [10.0] * 2
sigma = [3.0] * 2
nu = 3.5
R = ot.CorrelationMatrix([[1.0, 0.5], [0.5, 1.0]])
X = ot.Student(nu, mu, sigma, R)
```
you can compare the isoprobabilistic transformation, which is the generalized Nataf transformation associated to a Student(nu, 2) standard distribution, to the Rosenblatt transformation, associated to the Normal(2) distribution. To build the Rosenblatt transformation, use:
```
T = ot.Function(ot.RosenblattEvaluation(X))
```

**Comment by mbaudin47** [comment]
Thank you for the suggestions: I updated the script accordingly. I have approximately no idea about the useful options of the `View` class. I did not know about the `RosenblattEvaluation`: I have to see this in more details before creating an example.

**Comment by regislebrun** [comment]
Concerning the View class, help(otv.View) gives you a lot of information ;-)

**Comment by josephmure** [comment]
Here is a better formatted version of Michael's example, together with [the resulting HTML file](https://491-187032617-gh.circle-artifacts.com/0/html/auto_reliability_sensitivity/reliability/plot_standard_event.html).
```
"""
Map a sample or an event to the standard space
==============================================

The FORM/SORM recipe has several ingredients,
but certainly one of the most fundamental is the transformation
from physical space (or X-space) to standard space (or U-space).
This is performed by the :class:`~openturns.StandardEvent` class.

The present example shows how the transformation affects
a multivariate normal distribution. It illustrates one of its main properties:
**rotational invariance**.

"""

# %%
import openturns as ot
from openturns.viewer import View
ot.Log.Show(ot.Log.NONE)

# %%
# Set a distribution in the physical space.

mu = [10.0] * 2
sigma = [3.0] * 2
R = ot.CorrelationMatrix([[1.0, 0.5], [0.5, 1.0]])
c = ot.NormalCopula(R)
X1 = ot.Normal(mu[0], sigma[0])
X1.setDescription([r"$x_1$"])
X2 = ot.Normal(mu[1], sigma[1])
X2.setDescription([r"$x_2$"])
distribution_X = ot.ComposedDistribution([X1, X2], c)

# %%
# Get the corresponding standard distribution.

distribution_U = distribution_X.getStandardDistribution()
distribution_U.setDescription([r"$u_1$", r"$u_2$"])

# %%
# Draw the PDF of the distribution in the physical space.

graph_X = distribution_X.drawPDF()
scientific_legend = ['{:.3e}'.format(float(x)) for x in graph_X.getLegends()]
graph_X.setLegends(scientific_legend)
legend_kw = {'bbox_to_anchor':(1,1), 'loc':"upper left"}
view = View(graph_X, square_axes=True, legend_kw=legend_kw)

# %%
# Draw the PDF of the corresponding standard distribution.
graph_U = distribution_U.drawPDF()
scientific_legend = ['{:.3e}'.format(float(x)) for x in graph_U.getLegends()]
graph_U.setLegends(scientific_legend)
view = View(graph_U, square_axes=True, legend_kw=legend_kw)

# %%
# Map a sample from the physical space to the standard space.

sample_X = distribution_X.getSample(10000)
transformation = distribution_X.getIsoProbabilisticTransformation()
sample_U = transformation(sample_X)

# %%
# Plot the original sample - the one in the physical space.
bb = graph_X.getBoundingBox()
cloud = ot.Cloud(sample_X)
cloud.setPointStyle("dot")
graph_X.add(cloud)
graph_X.setTitle("Sample in the physical space")
graph_X.setLegends([""])
low = bb.getLowerBound()[0]
up = bb.getUpperBound()[0]
view = View(graph_X, square_axes=True)._ax[0].axis([low, up, low, up])

# %%
# Plot the transformed sample - the one in the standard space.

# sphinx_gallery_thumbnail_number = 4
bb = graph_U.getBoundingBox()
cloud = ot.Cloud(sample_U)
cloud.setPointStyle("dot")
graph_U.add(cloud)
graph_U.setTitle("Sample in the standard space")
graph_U.setLegends([""])
low = bb.getLowerBound()[0]
up = bb.getUpperBound()[0]
view = View(graph_U, square_axes=True)._ax[0].axis([low, up, low, up])

# %%
# Define a limit state function.

formula = "2.5 - (x1 - x2) + (x1 + x2)^2"
limitStateFunction = ot.SymbolicFunction(["x1", "x2"], [formula])

# %%
# Set the event "the limit state function is nonpositive".
threshold = 0.0
random_vector = ot.RandomVector(distribution_X)
lsf_random_vector = ot.CompositeRandomVector(limitStateFunction, random_vector)
event = ot.ThresholdEvent(lsf_random_vector, ot.LessOrEqual(), threshold)

# %%
# Compute the corresponding event in the standard space.
myStandardEvent = ot.StandardEvent(event)
```
![image](https://user-images.githubusercontent.com/31989332/114522224-75eadc00-9c43-11eb-963f-acea685dd084.png)

Unfortunately, it is still not complete. In particular, I do not see how it showcases rotational invariance. Any thoughts @mbaudin47 ?

**Comment by mbaudin47** [comment]
The distribution must be spherical in the standard space. More precisely, the density must depend only on the Euclidian norm of the parameter u. This is seen from the circular shape of the contours of the PDF in the U space. I should have written this in the text, but I realize that I didn't: may you insert these sentences in the example, and the example is complete, isn'it it?

**Comment by josephmure** [comment]
My PR is already merged, so I have no ready branch to put it on. I think I will let you commit this: it is your example after all!

**Comment by josephmure** [comment]
Another thing: perhaps the graphs would look better if we inserted the line ``view.getFigure().tight_layout()``after the first and second calls to `View`. The legends seem to be slightly cropped to the right.
