### ISSUE TITLE
Bug with two-output Kriging

### ISSUE THREAD

**Issue by mdelozzo** [openturns/openturns#2363]
I can no longer build a two-output Kriging with openturns 1.21 (it worked with 1.20.post3 and lower). Has the API changed? Am I doing something wrong? You will find below a reproducer with the associated error message.

Thanks in advance for your support.

# The traceback

```
WRN - Warning! For coherency we set scale upper bounds = [2,100,100]
Traceback (most recent call last):
  File "C:\Users\matthias.delozzo\workspace\GEMSEO\gemseo-mlearning\sandbox\issue_1.py", line 25, in <module>
    algo = KrigingAlgorithm(sampleX, sampleY, covarianceModel, basis)
  File "C:\Users\matthias.delozzo\workspace\GEMSEO\gemseo-mlearning\.tox\py39\lib\site-packages\openturns\metamodel.py", line 5273, in __init__
    _metamodel.KrigingAlgorithm_swiginit(self, _metamodel.new_KrigingAlgorithm(*args))
TypeError: InvalidArgumentException : In GeneralLinearModelAlgorithm::GeneralLinearModelAlgorithm, output sample dimension=2 does not match basis[=0] dimension=1
```

# The reproducer

```python
from matplotlib import pyplot as plt
from numpy import array
from numpy import cos
from numpy import hstack
from numpy import linspace
from numpy import newaxis
from numpy import pi
from numpy import sin
from openturns import KrigingAlgorithm
from openturns import LinearBasisFactory
from openturns import Sample
from openturns import SquaredExponential
from openturns import TensorizedCovarianceModel

# Generate the learning samples
x = linspace(0,1,10)[:,newaxis]
y1 = sin(2*pi*x)
y2 = cos(2*pi*x)
sampleX = Sample(x)
sampleY = Sample(hstack((y1,y2)))

# Build the model
covarianceModel = TensorizedCovarianceModel([SquaredExponential(),SquaredExponential()])
basis = LinearBasisFactory(1).build()
algo = KrigingAlgorithm(sampleX, sampleY, covarianceModel, basis)
algo.run()
model = algo.getResult().getMetaModel()

# Use the model
y = array(model(sampleX))
xt = linspace(0,1,100)[:,newaxis]
yt = array(model(xt))

fig, (ax1, ax2) = plt.subplots(1,2)
ax1.plot(x, y1, "sb")
ax1.plot(x, y[:,0], "or")
ax1.plot(xt, yt[:,0], "r")
ax2.plot(x, y2, "sb")
ax2.plot(x, y[:,1], "or")
ax2.plot(xt, yt[:,1], "r")
plt.show()
```

**Comment by mdelozzo** [comment]
Replacing 
```python
basis = LinearBasisFactory(1).build()
```
by
```python
basis = LinearBasisFactory(1).build()
basis = Basis(
    [
        AggregatedFunction([basis.build(k)] * 2)
        for k in range(basis.getSize())
    ]
)
```
works with 1.21 (even if the predictions are quite different from the original script with 1.20.post3) but fails with 1.20.post3:
```
WRN - Warning! For coherency we set scale upper bounds = [2,100,100]
WRN - Expected a basis of scalar functions, but first function has dimension 2. Only the first output component will be taken into account.
WRN - The basis of functions will be applied to all output marginals
Traceback (most recent call last):
  File "...\script.py", line 37, in <module>
    algo.run()
  File "...\openturns\metamodel.py", line 4912, in run
    return _metamodel.KrigingAlgorithm_run(self)
TypeError: InvalidArgumentException : Error: the function with index 1 has output dimension 2, but it should be 1.
```

**Comment by sofianehaddad** [comment]
@mdelozzo have a look at [this example](https://openturns.github.io/openturns/latest/auto_meta_modeling/kriging_metamodel/plot_kriging_multioutput_firesatellite.html#sphx-glr-auto-meta-modeling-kriging-metamodel-plot-kriging-multioutput-firesatellite-py). 
Since `1.21` new feature consists in using a basis (and no more a collection of basis) with each item of that basis being a vectorial function.
You will probably get different results as we also fixed a bug. Hope the new results are "better"

**Comment by mdelozzo** [comment]
Thanks for your answer. I understand why my code no longer works and why the code of my second comment only works from 1.21!

The documentation has to be updated because the current version says that the `KrigingAlgorithm` can use a sequence of `Basis`.

In my example, the Kriging was clearly better with 1.20 but the `SquaredExponential` covariance model is not the best one to approximate sinus and cosinus. So not sure that it is a problem. With Matern, the results are very good. If you want, I can add a picture before/after

**Comment by sofianehaddad** [comment]
yes thanks. What kind of `Basis` are you using (and in `1.20`)?
I guess the only case where there is no difference is for `ConstantBasis`. If there are some scripts you can share I can take a deeper look
Thanks again

**Comment by jschueller** [comment]
strange, I still get the (good) graph #2 with 1.21, but on linux

**Comment by jschueller** [comment]
I think the basis terms must be independent on the 2 components, with this I get the same curve:
```
basis = Basis(
    [AggregatedFunction([basis.build(0),basis.build(k)]) for k in range(basis.getSize())]
  + [AggregatedFunction([basis.build(k),basis.build(0)]) for k in range(basis.getSize())]
)
```

**Comment by sofianehaddad** [comment]
@mdelozzo did you change something in the `1.21` script? I can not reproduce your bug
I have the same output as "before"

**Comment by jschueller** [comment]
it gives the same result with the 1.21 script on linux, but not on windows, unless using my basis fix

**Comment by sofianehaddad** [comment]
Strange
Could you please add these lines at the begining & share the output file 
``` python
from openturns import Log
Log.Show(Log.ALL)
Log.SetFile("debug.txt")
```
I'd like to understand why we get this issue?

**Comment by jschueller** [comment]
[debug.txt](https://github.com/openturns/openturns/files/12498091/debug.txt)

**Comment by mdelozzo** [comment]
Sorry for the delay, I was on vacation.

Under windows, in the version 1.21 of [this comment](https://github.com/openturns/openturns/issues/2363#issuecomment-1674317227), I replaced
```python
basis = Basis(
    [
        AggregatedFunction([basis.build(k), basis.build(k)])
        for k in range(basis.getSize())
    ]
)
```
by 
```python
basis = Basis(
    [
        AggregatedFunction([basis.build(0), basis.build(k)])
        for k in range(basis.getSize())
    ]
    + [
        AggregatedFunction([basis.build(k), basis.build(0)])
        for k in range(basis.getSize())
    ]
)
```
and it works as expected with the version 1.20.

**Comment by sofianehaddad** [comment]
I am still trying to understand why this issue is windows specific. The `debug` file provided by Julien helps a bit but I need to run it on a platform step by step. The thing is `TensorizedCovarianceModel` is a bit complex & after `n` iterations it is difficult to see which parameter is used because `TensorizedCovarianceModel.setParameter` updates the parameter changing some values, updating others using the `*` operator...

I will try to reproduce it next weeks...

**Comment by jschueller** [comment]
its probably not worth the effort as it might come down to some small numerical diff,
the way the basis was given with dependent components is fishy enough to explain these results to me
